/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package Controller.Character;

import Model.Dice;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *This is th test class for the controller Ability Score generation.
 * It also tests all the dice values generated by the dice class since we cannot
 * test a final class directly.
 * @author khushnuma
 * @version 1.0.0
 */
public class AbilityScoreGenerationTest {

    public AbilityScoreGenerationTest() {
    }

    @BeforeClass
    public static void setUpClass() throws Exception {
    }

    @AfterClass
    public static void tearDownClass() throws Exception {
    }

    @Before
    public void setUp() {
    }

    @After
    public void tearDown() {
    }

    /**
     * Test of createAbilityList method, of class AbilityScoreGeneration.
     */
    @Test
    public void testCreateAbilityList() {
        System.out.println("createAbilityList -  sorted list of ability scores");
        AbilityScoreGeneration instance = new AbilityScoreGeneration();
        
        int[] result = instance.createAbilityList();
        assertEquals("List of six values",6, result.length);

        assertTrue(result[0]<= result[1]);
        assertTrue(result[1]<= result[2]);
        assertTrue(result[2]<= result[3]);
        assertTrue(result[3]<= result[4]);
        assertTrue(result[4]<= result[5]);
    }
    /**
     * Test of d10Dice method, of class Dice.
     */
    @Test
    public void testD10Dice() {
        System.out.println("d10Dice Test - value from 1 to 10.\n");
        int result = Dice.d10Dice();
        assertTrue(result > 0);
        assertTrue(result < 11);

    }

    /**
     * Test of d8Dice method, of class Dice.
     */
    @Test
    public void testD8Dice() {
        System.out.println("d8Dice Test - value from 1 to 8 \n");
        int result = Dice.d8Dice();
        assertTrue(result > 0);
        assertTrue(result < 9);
    }

    /**
     * Test of d6Dice method, of class Dice.
     */
    @Test
    public void testD6Dice() {
        System.out.println("d6DiceTest - value from 1 to 6 \n");
        int result = Dice.d6Dice();
        assertTrue(result > 0);
        assertTrue(result < 7);
    }

    /**
     * Test of d20Dice method, of class Dice.
     */
    @Test
    public void testD20Dice() {
        System.out.println("d20Dice Test - value from 1 to 20 \n");
        int result = Dice.d20Dice();
        assertTrue(result > 0);
        assertTrue(result < 21);
    }

}