/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MapSetDialog.java
 *
 * Created on Oct 14, 2011, 2:50:54 AM
 */
package View.Map;
import java.lang.Integer;

/**
 * This is the map set dialog inherit the JDialog.
 * MapSetDialog method is used to create a new form MapSetDialog.
 * set the columns and rows.
 * 
 * @author yukywang
 */
public class MapSetDialog extends javax.swing.JDialog
{
    /** 
     * Creates new form MapSetDialog
     * Create the minimal and maximal number of the column and row.
     * Use getCols and getRows methods to retrieve the number after player selected.
     * 
     * @param pMin the minimal number begin of the column and row.
     * @param pMaxl the maximal number end of the column and row.
     * @author yukywang
     */
    public MapSetDialog(java.awt.Frame pParent, boolean pModal, int pMin,int pMaxl)
    {
        super(pParent, pModal);
        initComponents();
        for(int i = pMin; i <= pMaxl; i++)
        {
            _comboBoxCol.addItem(i);
            _comboBoxRow.addItem(i);
        }
        _comboBoxCol.setSelectedIndex(0);
        _comboBoxRow.setSelectedIndex(0);
    }
    
    /**
     * get selected columns 
     * @return the column number of map matrix
     */
    public int getCols()
    {
        return Integer.parseInt(_comboBoxCol.getSelectedItem().toString());
    }

    /**
     * get selected columns 
     * @return the column number of map matrix
     */
    public int getRows()
    {
        return Integer.parseInt(_comboBoxRow.getSelectedItem().toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _labelRow = new javax.swing.JLabel();
        _labelCol = new javax.swing.JLabel();
        _comboBoxRow = new javax.swing.JComboBox();
        _comboBoxCol = new javax.swing.JComboBox();
        _buttonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Map Size Setting");

        _labelRow.setText("Map Rows:");

        _labelCol.setText("Map Column:");

        _buttonOk.setText("OK");
        _buttonOk.setActionCommand("OK");
        _buttonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _buttonOkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(_buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_labelRow)
                            .addComponent(_labelCol))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(_comboBoxCol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_comboBoxRow, 0, 149, Short.MAX_VALUE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_comboBoxRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_labelRow)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_labelCol)
                            .addComponent(_comboBoxCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45)
                .addComponent(_buttonOk)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Set the value false when the mouse clicked the OK button.
     * 
     * @param evt the command line arguments
     * @author yukywang
     */
    private void _buttonOkMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event__buttonOkMouseClicked
    {//GEN-HEADEREND:event__buttonOkMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event__buttonOkMouseClicked

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _buttonOk;
    private javax.swing.JComboBox _comboBoxCol;
    private javax.swing.JComboBox _comboBoxRow;
    private javax.swing.JLabel _labelCol;
    private javax.swing.JLabel _labelRow;
    // End of variables declaration//GEN-END:variables
}
